repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        types: [go]
      - id: go-vet
        name: go vet
        entry: bash -c 'cd backend && go vet ./...'
        language: system
        types: [go]
        pass_filenames: false
